UNIT MATRIZ;
interface
USES Tipos;
FUNCTION CAMBIO(PALABRA:STRING):VARIABLESTERMINALES;
PROCEDURE CARGARM(VAR TASI:TAS);
Procedure INICIALIZARMATRIZ(var TASI:TAS);
implementation

FUNCTION CAMBIO(PALABRA:STRING):VARIABLESTERMINALES;
BEGIN
IF PALABRA='ID' THEN CAMBIO:=ID
ELSE IF PALABRA='(' THEN CAMBIO:=PARENTESISA
ELSE IF PALABRA=')'THEN CAMBIO:=PARENTESISB
ELSE IF PALABRA='.' THEN CAMBIO:=PUNTO
ELSE IF PALABRA=':' THEN CAMBIO:=DOSPUNTOS
ELSE IF PALABRA=',' THEN CAMBIO:=COMA
ELSE IF PALABRA='ASIGNACION1'THEN  CAMBIO:= ASIGNACION1
ELSE IF PALABRA='+' THEN CAMBIO:=SUMA
ELSE IF PALABRA='*' THEN CAMBIO:=MULT
ELSE IF PALABRA='/' THEN CAMBIO:=DIB
ELSE IF PALABRA='RAIZ'THEN CAMBIO:=RAIZ
ELSE IF PALABRA='POTEN'THEN CAMBIO:=POTEN
ELSE IF PALABRA='CONSTANTEREAL'THEN CAMBIO:=CONSTANTEREAL
ELSE IF PALABRA='CONSTANTECADENA'THEN CAMBIO:=CONSTANTECADENA
ELSE IF PALABRA='LEER'THEN CAMBIO:=LEER
ELSE IF PALABRA='MOSTRAR'THEN CAMBIO:=MOSTRAR
ELSE IF PALABRA='SI'THEN CAMBIO:=SI
ELSE IF PALABRA='SINO'THEN CAMBIO:=SINO
ELSE IF PALABRA='MIENTRAS'THEN CAMBIO:=MIENTRAS
ELSE IF PALABRA='PARA'THEN CAMBIO:=PARA
ELSE IF PALABRA='<'THEN CAMBIO:=MENOR
ELSE IF PALABRA='>'THEN CAMBIO:=MAYOR
ELSE IF PALABRA='>='THEN  CAMBIO:=MAYORI
ELSE IF PALABRA='<='THEN  CAMBIO:=MENORI
ELSE IF PALABRA='<>'THEN  CAMBIO:=DISTINTO
ELSE IF PALABRA='IGUAL'THEN  CAMBIO:=IGUAL
ELSE IF PALABRA='AN'THEN CAMBIO:=AN
ELSE IF PALABRA='O'THEN  CAMBIO:=O
ELSE IF PALABRA='FUNCION'THEN CAMBIO:=FUNCION
ELSE IF PALABRA='FIN' THEN CAMBIO:=FIN
ELSE IF PALABRA='HASTA' THEN CAMBIO:=HASTA
ELSE IF PALABRA='PESOS'THEN CAMBIO:=PESOS
ELSE IF PALABRA='PROGRAMA'THEN CAMBIO:=PROGRAMA
ELSE IF PALABRA='PROGRAMA1' THEN CAMBIO:=PROGRAMA1
ELSE IF PALABRA='FUCTION' THEN CAMBIO:=FUCTION
ELSE IF PALABRA='FUNCIONE'THEN CAMBIO:=FUNCIONE
ELSE IF PALABRA='PARAMETROS'THEN CAMBIO:=PARAMETROS
ELSE IF PALABRA='PARAMETROS1'THEN CAMBIO:=PARAMETROS1
ELSE IF PALABRA='CUERPO' THEN CAMBIO:=CUERPO
ELSE IF PALABRA='CUERPO1' THEN CAMBIO:=CUERPO1
ELSE IF PALABRA='SENTENCIA' THEN CAMBIO:=SENTENCIA
ELSE IF PALABRA='ASIGNACION'THEN CAMBIO:=ASIGNACION
ELSE IF PALABRA='OPASIG' THEN CAMBIO:=OPASIG
ELSE IF PALABRA='EA' THEN CAMBIO:=EA
ELSE IF PALABRA='H' THEN CAMBIO:=H
ELSE IF PALABRA='T' THEN CAMBIO:=T
ELSE IF PALABRA='Y' THEN CAMBIO:=Y
ELSE IF PALABRA='Z' THEN CAMBIO:=Z
ELSE IF PALABRA='X' THEN CAMBIO:=X
ELSE IF PALABRA='D' THEN CAMBIO:=D
ELSE IF PALABRA='LECTURA'THEN CAMBIO:=LECTURA
ELSE IF PALABRA='ESCRITURA' THEN CAMBIO:=ESCRITURA
ELSE IF PALABRA='A' THEN CAMBIO:=A
ELSE IF PALABRA='B' THEN CAMBIO:=B
ELSE IF PALABRA='II' THEN CAMBIO:=II
ELSE IF PALABRA='IF1' THEN CAMBIO:=IF1
ELSE IF PALABRA='WHIL' THEN CAMBIO:=WHIL
ELSE IF PALABRA='FO' THEN CAMBIO:=FO
ELSE IF PALABRA='COND' THEN CAMBIO:=COND
ELSE IF PALABRA='COND1' THEN CAMBIO:=COND1
ELSE IF PALABRA='EE' THEN CAMBIO:=EE
ELSE IF PALABRA='P' THEN CAMBIO:=P
ELSE IF PALABRA='OPREL' THEN CAMBIO:=OPREL
ELSE IF PALABRA='OPLOG' THEN CAMBIO:=OPLOG
ELSE IF PALABRA='BLOQUE' THEN CAMBIO:=BLOQUE
ELSE IF PALABRA='EPSILON' THEN CAMBIO:=EPSILON
ELSE IF PALABRA='R' THEN CAMBIO:=R
ELSE IF PALABRA='PARAMETROS2' THEN CAMBIO:=PARAMETROS2
ELSE IF PALABRA='PARAMETROS3' THEN CAMBIO:=PARAMETROS3;
END;

Procedure INICIALIZARMATRIZ (var TASI:TAS);
Var
   I,J:VARIABLESTERMINALES;
Begin
     For I:=PROGRAMA to BLOQUE do
     Begin
        For J:=ID to PESOS do
        Begin
          TASI[I,J]:='';
        end;
     end;
end;

PROCEDURE CARGARM(VAR TASI:TAS);
BEGIN
TASI[PROGRAMA,FUNCION]:='PROGRAMA1 FUCTION';

TASI[PROGRAMA1,FUNCION]:='PROGRAMA1 FUCTION';
TASI[PROGRAMA1,PESOS]:='EPSILON';

TASI[FUCTION,FUNCION]:='BLOQUE ) PARAMETROS ( FUNCIONE';
TASI[FUNCIONE,FUNCION]:='ID FUNCION';

TASI[PARAMETROS,ID]:='PARAMETROS1 ID';
TASI[PARAMETROS1,PARENTESISB]:='EPSILON';
TASI[PARAMETROS1,COMA]:='PARAMETROS1 ID ,';


TASI[PARAMETROS2,ID]:='PARAMETROS3 EA';
TASI[PARAMETROS2,PARENTESISB]:='PARAMETROS3 EA';
TASI[PARAMETROS2,RAIZ]:='PARAMETROS3 EA';
TASI[PARAMETROS2,CONSTANTEREAL]:='PARAMETROS3 EA';

TASI[PARAMETROS3,COMA]:='PARAMETROS3 EA ,';
TASI[PARAMETROS3, PARENTESISB]:='EPSILON';

TASI[CUERPO,ID]:='CUERPO1 SENTENCIA';
TASI[CUERPO,LEER]:='CUERPO1 SENTENCIA';
TASI[CUERPO,MOSTRAR]:='CUERPO1 SENTENCIA';
TASI[CUERPO,SI]:='CUERPO1 SENTENCIA';
TASI[CUERPO,MIENTRAS]:='CUERPO1 SENTENCIA';
TASI[CUERPO,PARA]:='CUERPO1 SENTENCIA';

TASI[CUERPO1,ID]:='CUERPO1 SENTENCIA';
TASI[CUERPO1,LEER]:='CUERPO1 SENTENCIA';
TASI[CUERPO1,MOSTRAR]:='CUERPO1 SENTENCIA';
TASI[CUERPO1,SI]:='CUERPO1 SENTENCIA';
TASI[CUERPO1,MIENTRAS]:='CUERPO1 SENTENCIA';
TASI[CUERPO1,PARA]:='CUERPO1 SENTENCIA';
TASI[CUERPO1,FIN]:='EPSILON';
TASI[CUERPO1,SINO]:='EPSILON';

TASI[SENTENCIA,ID]:='ASIGNACION';
TASI[SENTENCIA,LEER]:='LECTURA';
TASI[SENTENCIA,MOSTRAR]:='ESCRITURA';
TASI[SENTENCIA,SI]:='II';
TASI[SENTENCIA,MIENTRAS]:='WHIL';
TASI[SENTENCIA,PARA]:='FO';

TASI[ASIGNACION,ID]:='. EA OPASIG ID';

TASI[OPASIG,ASIGNACION1]:='ASIGNACION1';

TASI[EA,ID]:='H T';
TASI[EA,PARENTESISA]:='H T';
TASI[EA,RAIZ]:='H T';
TASI[EA,CONSTANTEREAL]:='H T';

TASI[H,PARENTESISB]:='EPSILON';
TASI[H,PUNTO]:='EPSILON';
TASI[H,DOSPUNTOS]:='EPSILON';
TASI[H,SUMA]:='H T +';
TASI[H,MAYOR]:='EPSILON';
TASI[H,MENOR]:='EPSILON';
TASI[H,MAYORI]:='EPSILON';
TASI[H,MENORI]:='EPSILON';
TASI[H,DISTINTO]:='EPSILON';
TASI[H,IGUAL]:='EPSILON';
TASI[H,AN]:='EPSILON';
TASI[H,O]:='EPSILON';
TASI[H,HASTA]:='EPSILON';
TASI[H,COMA]:='EPSILON';


TASI[T,ID]:='Y Z';
TASI[T,PARENTESISA]:='Y Z';
TASI[T,RAIZ]:='Y Z';
TASI[T,CONSTANTEREAL]:='Y Z';

TASI[Y,PARENTESISB]:='EPSILON';
TASI[Y,PUNTO]:='EPSILON';
TASI[Y,DOSPUNTOS]:='EPSILON';
TASI[Y,SUMA]:='EPSILON';
TASI[Y,MULT]:='Y Z *';
TASI[Y,DIB]:='Y Z /';
TASI[Y,MAYOR]:='EPSILON';
TASI[Y,MENOR]:='EPSILON';
TASI[Y,MAYORI]:='EPSILON';
TASI[Y,MENORI]:='EPSILON';
TASI[Y,DISTINTO]:='EPSILON';
TASI[Y,IGUAL]:='EPSILON';
TASI[Y,AN]:='EPSILON';
TASI[Y,O]:='EPSILON';
TASI[Y,HASTA]:='EPSILON';
TASI[Y,COMA]:='EPSILON';

TASI[Z,ID]:='X D';
TASI[Z,PARENTESISA]:='X D';
TASI[Z,RAIZ]:='X D RAIZ';
TASI[Z,CONSTANTEREAL]:='X D';

TASI[X,PARENTESISB]:='EPSILON';
TASI[X,PUNTO]:='EPSILON';
TASI[X,DOSPUNTOS]:='EPSILON';
TASI[X,SUMA]:='EPSILON';
TASI[X,MULT]:='EPSILON';
TASI[X,DIB]:='EPSILON';
TASI[X,POTEN]:='X D POTEN';
TASI[X,MAYOR]:='EPSILON';
TASI[X,MENOR]:='EPSILON';
TASI[X,MAYORI]:='EPSILON';
TASI[X,MENORI]:='EPSILON';
TASI[X,DISTINTO]:='EPSILON';
TASI[X,IGUAL]:='EPSILON';
TASI[X,AN]:='EPSILON';
TASI[X,O]:='EPSILON';
TASI[X,HASTA]:='EPSILON';
TASI[X,COMA]:='EPSILON';


TASI[D,ID]:='R ID';
TASI[D,PARENTESISA]:=') EA (';
TASI[D,CONSTANTEREAL]:='CONSTANTEREAL';

TASI[R,PARENTESISA]:=') PARAMETROS2 (';
TASI[R,PARENTESISB]:='EPSILON';
TASI[R,PUNTO]:='EPSILON';
TASI[R,DOSPUNTOS]:='EPSILON';
TASI[R,SUMA]:='EPSILON';
TASI[R,MULT]:='EPSILON';
TASI[R,DIB]:='EPSILON';
TASI[R,POTEN]:='EPSILON';
TASI[R,MAYOR]:='EPSILON';
TASI[R,MENOR]:='EPSILON';
TASI[R,MAYORI]:='EPSILON';
TASI[R,MENORI]:='EPSILON';
TASI[R,DISTINTO]:='EPSILON';
TASI[R,IGUAL]:='EPSILON';
TASI[R,AN]:='EPSILON';
TASI[R,O]:='EPSILON';
TASI[R,HASTA]:='EPSILON';
TASI[R,COMA]:='EPSILON';


TASI[LECTURA,LEER]:='. ) ID ( LEER';

TASI[ESCRITURA,MOSTRAR]:='. ) A ( MOSTRAR';

TASI[A,ID]:='ID';
TASI[A,CONSTANTECADENA]:='B CONSTANTECADENA';

TASI[B,PARENTESISB]:='EPSILON';
TASI[B,COMA]:='ID ,';


TASI[II,SI]:='IF1 CUERPO : COND SI';


TASI[IF1,SINO]:='BLOQUE SINO';
TASI[IF1,FIN]:='. FIN';

TASI[WHIL,MIENTRAS]:='BLOQUE : COND MIENTRAS';

TASI[FO,PARA]:='BLOQUE : EA HASTA EA IGUAL ID PARA';

TASI[COND,ID]:='COND1 EE';
TASI[COND,PARENTESISA]:='COND1 EE';
TASI[COND,RAIZ]:='COND1 EE';
TASI[COND,CONSTANTEREAL]:='COND1 EE';

TASI[COND1,DOSPUNTOS]:='EPSILON';
TASI[COND1,AN]:='COND OPLOG';
TASI[COND1,O]:='COND OPLOG';

TASI[EE,ID]:='P EA';
TASI[EE,PARENTESISA]:='P EA';
TASI[EE,CONSTANTEREAL]:='P EA';
TASI[EE,RAIZ]:='P EA';

TASI[P,MENOR]:='EA OPREL';
TASI[P,MAYOR]:='EA OPREL';
TASI[P,MENORI]:='EA OPREL';
TASI[P,MAYORI]:='EA OPREL';
TASI[P,DISTINTO]:='EA OPREL';
TASI[P,IGUAL]:='EA OPREL';

TASI[OPREL,MENOR]:='<';
TASI[OPREL,MAYOR]:='>';
TASI[OPREL,MENORI]:='<=';
TASI[OPREL,MAYORI]:='>=';
TASI[OPREL,DISTINTO]:='<>';
TASI[OPREL,IGUAL]:='IGUAL';

TASI[OPLOG,AN]:='AN';
TASI[OPLOG,O]:='O';

TASI[BLOQUE,ID]:='. FIN CUERPO' ;
TASI[BLOQUE,LEER]:='. FIN CUERPO' ;
TASI[BLOQUE,MOSTRAR]:='. FIN CUERPO';
TASI[BLOQUE,SI]:='. FIN CUERPO'      ;
TASI[BLOQUE,MIENTRAS]:='. FIN CUERPO'  ;
TASI[BLOQUE,PARA]:='. FIN CUERPO'       ;
END;

end.
