unit Tipos;

interface

const
q0=0;
MAX=30;
MAXP=9;

type                              
VariablesTerminales=(ID,PARENTESISA,PARENTESISB,PUNTO,DOSPUNTOS,COMA,ASIGNACION1,SUMA,MULT,DIB,RAIZ,POTEN,CONSTANTEREAL,CONSTANTECADENA,LEER,
MOSTRAR,SI,SINO,MIENTRAS,PARA,MENOR,MAYOR,MAYORI,MENORI,DISTINTO,IGUAL,AN,O,FUNCION,FIN,HASTA,PESOS,EPSILON,FINDEARCHIVO,ERRORLEXICO,PROGRAMA,PROGRAMA1,FUCTION,FUNCIONE,
PARAMETROS,PARAMETROS1,CUERPO,CUERPO1,SENTENCIA,ASIGNACION,OPASIG,EA,R,PARAMETROS2,PARAMETROS3,H,T,Y,Z,X,D,LECTURA,ESCRITURA,A,B,II,IF1,CASO,CASO1,WHIL,FO,COND,COND1,EE,P,OPREL,OPLOG,BLOQUE,NO);

CONST
NVOT:ARRAY[VARIABLESTERMINALES] OF STRING=('ID','PARENTESISA','PARENTESISB','PUNTO','DOSPUNTOS','COMA','ASIGNACION1','SUMA','MULT','DIB','RAIZ','POTEN','CONSTANTEREAL','CONSTANTECADENA','LEER',
'MOSTRAR','SI','SINO','MIENTRAS','PARA','MENOR','MAYOR','MAYORI','MENORI','DISTINTO','IGUAL','AN','O','FUNCION','FIN','HASTA','PESOS','EPSILON','FINDEARCHIVO','ERRORLEXICO','PROGRAMA','PROGRAMA1','FUCTION','FUNCIONE',
'PARAMETROS','PARAMETROS1','CUERPO','CUERPO1','SENTENCIA','ASIGNACION','OPASIG','EA','R','PARAMETROS2','PARAMETROS3','H','T','Y','Z','X','D','LECTURA','ESCRITURA','A','B','II','IF1','CASO','CASO1','WHIL','FO','COND','COND1','EE','P','OPREL','OPLOG','BLOQUE','NO');

TYPE

tfuente=file of char;
Terminales=ID..ERRORLEXICO;
VARIABLES=PROGRAMA..BLOQUE;

TAS=ARRAY[PROGRAMA..BLOQUE,ID..PESOS] OF STRING;

TipoTabla=record
	lexema:string;
	valor:REAL;
	componente:Terminales;
end;

TPuntero=^Tnodo;

TNODO=RECORD
	INFO:TIPOTABLA;
	SIG:TPUNTERO;
END;

Lista=Record
	Cab:TPuntero;
	Tam:Word;
end;

PARBOL=^ARBOL;

ARBOL=record
	vot:variableSterminalES;
	lexema:string;
	cantidadhijos:0..MAXP;
	HIJOS:ARRAY[1..MAXP] OF PARBOL;
END;

TIPOP=RECORD
	VOT:VARIABLESTERMINALES;
	APUNTA:PARBOL;
END;

PILAT=RECORD
	Elem:ARRAY[1..MAX] OF TIPOP;
	Tope:0..MAX;
END;


TLF=RECORD
	LEXEMA:STRING;
	APUNTADOR:PARBOL;
END;

LFs=RECORD
	INFO:ARRAY[1..20] OF TLF;
	TAM:BYTE;
END;

VECTORPARAMETROS=ARRAY[1..10] OF REAL;

implementation

begin

end.
